/**
 * MQTT Dashboard
 * MQTT
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Sensor } from '../model/sensor';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class MqttService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * get user
     * returns measurements
     * @param topicName 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getData(topicName: string, observe?: 'body', reportProgress?: boolean): Observable<Sensor>;
    public getData(topicName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Sensor>>;
    public getData(topicName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Sensor>>;
    public getData(topicName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (topicName === null || topicName === undefined) {
            throw new Error('Required parameter topicName was null or undefined when calling getData.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Sensor>('get',`${this.basePath}/mqtt/measurements/${encodeURIComponent(String(topicName))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * subscribe
     * subscribe to topic
     * @param topicName 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public subscribeChannel(topicName: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public subscribeChannel(topicName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public subscribeChannel(topicName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public subscribeChannel(topicName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (topicName === null || topicName === undefined) {
            throw new Error('Required parameter topicName was null or undefined when calling subscribeChannel.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('post',`${this.basePath}/mqtt/subscribe/${encodeURIComponent(String(topicName))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * unsubscribe
     * unsubscribe to topic
     * @param topicName 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public unsubscribeChannel(topicName: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public unsubscribeChannel(topicName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public unsubscribeChannel(topicName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public unsubscribeChannel(topicName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (topicName === null || topicName === undefined) {
            throw new Error('Required parameter topicName was null or undefined when calling unsubscribeChannel.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('post',`${this.basePath}/mqtt/unsubscribe/${encodeURIComponent(String(topicName))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
